name: Check
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: test ${{ matrix.py }} ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
          - "3.8"
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - name: setup python for tox
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install tox-uv
        run: python -m pip install tox-uv
      - uses: moonrepo/setup-rust@v1
        with:
          cache-base: main
          bins: cargo-tarpaulin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
          allow-prereleases: true
      - name: setup test suite
        run: tox run -vv --notest --skip-missing-interpreters false -e ${{ matrix.py }}
      - name: run test suite
        run: tox run  --skip-pkg-install -e ${{ matrix.py }}

  check:
    name: tox env ${{ matrix.tox_env }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tox_env:
          - type
          - dev
          - readme
    steps:
      - uses: actions/checkout@v4
      - name: setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install tox-uv
        run: python -m pip install tox-uv
      - uses: moonrepo/setup-rust@v1
        with:
          cache-base: main
      - name: Setup test suite
        run: tox -vv --notest --skip-missing-interpreters false -e ${{ matrix.tox_env }}
      - name: Run test suite
        run: tox --skip-pkg-install -e ${{ matrix.tox_env }}
